# Site settings
title: "지켜보고 있다 대한민국 재정"
email: contact@codenamu.org
description: > # this means to ignore newlines until "baseurl:"
  투명 재정 프로젝트는 정부가 공개한 재정 데이터를 시민들이 직접 활용해서 의미 있는 결과물을 만들어보자는 취지에서 추진한 정부와 시민들의 협업 프로젝트입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://transparency.codenamu.org" # the base hostname & protocol for your site
twitter_username: codenamu
github_username:  codenamu

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: true

# collections
collections:
  project:
    output: true
    permalink: /project/:path/

defaults:
  -
    scope:
      path: _project
    values:
      layout: project
      splash: projects-splash.jpg|지켜보고 있다 대한민국 재정
      type: project
